version: 2
jobs:
  build:
    working_directory: pixelgroup-home-two-dot-o
    environment:
      IMAGE_TAG: ${CIRCLE_SHA1}-${CIRCLE_BUILD_NUM}
      COMPOSE_PROJECT_NAME: ${CIRCLE_BUILD_NUM}

    # In 2.0, we specify our Ruby version by using a public Docker image
    docker:
       - image: library/docker:17



    steps:
      - checkout

      - setup_remote_docker
      
      - run: docker build -t {GH-USER}/{GH-REPO}-uwsgi:${CIRCLE_SHA1}-${CIRCLE_BUILD_NUM} uwsgi
      - run: docker build -t {GH-USER}/{GH-REPO}-nginx:${CIRCLE_SHA1}-${CIRCLE_BUILD_NUM} nginx
      - run: docker build -t {GH-REPO}-test test
      - run: xxd -l 8 -p /dev/urandom > test_container_name

      - run: docker-compose up -d
      - run: docker run --link ${CIRCLE_BUILD_NUM}_nginx_1:nginx --name $(cat test_container_name) {GH-REPO}-test
      - run: docker cp $(cat test_container_name):/nosetests.xml $CIRCLE_TEST_REPORTS
      - run: docker-compose kill || true
# deployment:
#   staging:
#     branch: master
#     commands:
#       - docker login -u $DOCKER_USER -e $DOCKER_EMAIL -p $DOCKER_PASS
#       - docker push {GH-USER}/{GH-REPO}-uwsgi:$IMAGE_TAG
#       - docker push {GH-USER}/{GH-REPO}-nginx:$IMAGE_TAG
#       - script/update-trello.sh
#       - script/deploy.sh prod
