uwsgi:
  image: "{GH-USER}/{GH-REPO}-uwsgi:${CIRCLE_SHA1}-${CIRCLE_BUILD_NUM}"
nginx:
  image: "{GH-USER}/{GH-REPO}-nginx:${CIRCLE_SHA1}-${CIRCLE_BUILD_NUM}"
  links:
    - uwsgi
  expose:
    - 8000
